core/urls.py
# core/urls.py

from django.urls import include, path

from . import views

app_name = "core"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("add", views.ParserInsertView.as_view(), name="add"),
    path("about", views.AboutView.as_view(), name="about"),
    path("search", views.SearchView.as_view(), name="search"),
    path("recipe/<int:recipe_id>", views.RecipeView.as_view(), name="detail"),
    path("recipe/<int:recipe_id>/edit", views.EditView.as_view(), name="edit"),
    path("recipe/<int:recipe_id>/delete", views.DeleteView.as_view(), name="delete"),
]

nomsable/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404

handler404 = 'core.views.error_404_view'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls', namespace='core')),
]

core/models.py
from django.db import models

from accounts.models import User


class Ingredient(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return '<Ingredient name="{}">'.format(self.name)


class Tag(models.Model):
    name = models.CharField(max_length=255)


class Recipe(models.Model):
    # Fields from schema.org/Recipe
    name = models.CharField(max_length=255)
    description = models.TextField()
    image = models.URLField(blank=True, null=True)
    # cooking_method = models.CharField(max_length=255)
    prep_time = models.DurationField(blank=True, null=True)
    cook_time = models.DurationField(blank=True, null=True)
    total_time = models.DurationField(blank=True, null=True)
    # nutrition = models.JSONField
    author = models.CharField(max_length=255)
    keywords = models.JSONField(
        default=list, blank=True
    )  # from schema.org / just for search
    publisher = models.CharField(max_length=255)
    publisher_url = models.URLField(blank=True, null=True)
    origin_url = models.URLField(blank=True, null=True)

    # custom fields
    tags = models.ManyToManyField(Tag, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_edited = models.DateTimeField(auto_now=True)
    added_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    @classmethod
    def get_all_filtered(cls, user):
        return cls.objects.filter(
            ~models.Q(tags__in=user.preferences.hidden_recipe_tags.all()),
            ~models.Q(
                ingredients__ingredient__in=user.preferences.hidden_recipe_ingredients.all()
            ),
        )


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name="ingredients"
    )
    ingredient = models.ForeignKey(Ingredient, on_delete=models.PROTECT)
    quantity = models.FloatField(null=True, blank=True)
    description = models.CharField(max_length=255, null=True, blank=True)


class RecipeInstruction(models.Model):
    class Meta:
        ordering = ["step_no"]
        constraints = [
            models.UniqueConstraint(
                fields=["recipe", "step_no"], name="unique_recipe_step_nos"
            )
        ]

    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name="instructions"
    )
    step_no = models.IntegerField()
    text = models.TextField()
    # ingredients = models.ManyToManyField(RecipeIngredient)

core/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import (
    ModelForm,
    formset_factory,
    inlineformset_factory,
    modelformset_factory,
    widgets,
)

from core.models import Ingredient, Recipe, RecipeIngredient, RecipeInstruction, Tag


class ParserInsertForm(forms.Form):
    url = forms.URLField(label="website url")


class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        fields = [
            "name",
            "description",
            "prep_time",
            "cook_time",
            "total_time",
            "image",
            "author",
            "origin_url",
            "publisher",
            "publisher_url",
        ]
        widgets = {
            "name": forms.TextInput(
                attrs={
                    "style": "line-height: 1.2; font-size: 3.2rem; margin-top: 0.46rem; height: 4.6rem;"
                }
            ),
            "description": forms.Textarea(attrs={"style": "height: inherit;"}),
        }


class IngredientForm(ModelForm):
    # recipe_id = forms.CharField()
    ingredient = forms.CharField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.initial.get("ingredient") is not None:
            self.initial["ingredient"] = Ingredient.objects.get(
                pk=self.initial["ingredient"]
            ).name

    def clean_ingredient(self):
        try:
            ingredient = self.cleaned_data["ingredient"]
        except AttributeError:
            raise ValidationError("Couldn't find ingredient uwu")
        obj, _ = Ingredient.objects.get_or_create(name=ingredient)
        return obj


class SearchForm(forms.Form):
    search = forms.CharField(
        label="search", widget=forms.TextInput(attrs={"placeholder": "search"})
    )


IngredientFormSet = modelformset_factory(
    RecipeIngredient,
    fields=("ingredient", "quantity", "description"),
    form=IngredientForm,
    widgets={
        "quantity": forms.TextInput(),
    },
    can_delete=True,
)

InstructionFormSet = modelformset_factory(
    RecipeInstruction,
    fields=("step_no", "text"),
    can_delete=True,
)


class RecipeTagForm(forms.ModelForm):
    tag = forms.CharField(label="Tags")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.initial.get("tag") is not None:
            self.initial["tag"] = Tag.objects.get(pk=self.initial["tag"]).name

    def clean_tag(self):
        tag, _ = Tag.objects.get_or_create(name=self.cleaned_data["tag"])
        return tag


RecipeTagFormSet = inlineformset_factory(
    Recipe,
    Recipe.tags.through,
    fields=("tag",),
    form=RecipeTagForm,
    extra=1,
    can_delete=True,
    can_delete_extra=True,
)

core/views.py
import datetime
import json
import operator
import random
import re
from datetime import datetime, timedelta
from functools import reduce

import isodate
import requests
from bs4 import BeautifulSoup
from django.db.models import Q
from django.http import Http404
from django.shortcuts import redirect, render
from django.views import View
from django.views.generic import TemplateView

from accounts.helper import LoginRequiredMixin
from core.forms import (
    IngredientFormSet,
    InstructionFormSet,
    ParserInsertForm,
    RecipeForm,
    RecipeTagFormSet,
    SearchForm,
)
from core.models import Ingredient, Recipe, RecipeIngredient, RecipeInstruction


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = "core/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        recipes = Recipe.get_all_filtered(self.request.user)
        context["cook_next_recipes"] = random.sample(
            list(recipes), min(5, recipes.count())
        )
        context["greeting"] = random.choice(
            [
                "welcome back",
                "welcome",
                "willkommen",
                "bonjour",
                "salut!",
                "hey",
                "hi",
                "hello",
                "howdy",
                "mew",
                "heyyy",
                "hiya",
                "kama pona",
                "pona!",
                "o!",
                "greetings",
                "你好",
                "long-time no see",
                "sup",
                "good to see you",
                "hoi",
                "¡hola",
                "¡hi",
                "servus",
                "gude",
            ]
        )
        context["greeting_emoji"] = random.choices(
            population=[
                "",
                ":3",
                "🐈",
                "=^-^=",
                ":3~",
                "⁼^⁻^⁼",
                "purr~",
            ],
            weights=[
                0.2,
                0.4,
                0.1,
                0.1,
                0.1,
                0.05,
                0.05,
            ],
            k=1,
        )[0]
        context["search_form"] = SearchForm()
        context["latest_recipes"] = Recipe.get_all_filtered(self.request.user).order_by(
            "-date_created"
        )[:5]
        return context


class SearchView(LoginRequiredMixin, View):
    template_name = "core/search.html"

    def get(self, request):
        return render(request, self.template_name, {"search_form": SearchForm})

    def post(self, request):
        query = SearchForm(request.POST)
        if not query.is_valid():
            return render(
                request, "core/search.html", {"search_form": SearchForm}
            )  # add form errors
        search_term = re.split(" |,", query.cleaned_data["search"].lower())

        ingredient_term = []
        user_term = []
        publisher_term = []
        author_term = []
        time_gt_term = []
        time_lt_term = []
        time_eq_term = []
        title_term = []
        wildcard = False
        for term in search_term:
            if term.startswith("time:gt:"):
                t = datetime.strptime(term[8:], "%H:%M:%S")
                time_gt_term.append(
                    timedelta(hours=t.hour, minutes=t.minute, seconds=t.second)
                )
            elif term.startswith("time:lt:"):
                t = datetime.strptime(term[8:], "%H:%M:%S")
                time_lt_term.append(
                    timedelta(hours=t.hour, minutes=t.minute, seconds=t.second)
                )
            elif term.startswith("time:eq:"):
                t = datetime.strptime(term[8:], "%H:%M:%S")
                time_eq_term.append(
                    timedelta(hours=t.hour, minutes=t.minute, seconds=t.second)
                )
            elif term.startswith("ingredient:"):
                ingredient_term.append(term[11:])
            elif term.startswith("user:"):
                user_term.append(term[9:])
            elif term.startswith("author:"):
                author_term.append(term[7:])
            elif term.startswith("publisher:"):
                publisher_term.append(term[10:])
            elif term.startswith("*"):
                wildcard = True
            else:
                title_term.append(term)

        if wildcard:
            search_results = Recipe.objects.all()
        else:
            search_results = Recipe.objects.filter(
                reduce(
                    operator.and_,
                    (
                        Q(name__contains=x) | Q(description__contains=x)
                        for x in title_term
                    ),
                    ~Q(pk__in=[]),
                ),
                reduce(
                    operator.and_,
                    (
                        Q(ingredients__ingredient__name__contains=x)
                        | Q(ingredients__description__contains=x)
                        for x in ingredient_term
                    ),
                    ~Q(pk__in=[]),
                ),
                reduce(
                    operator.and_,
                    (Q(added_by__username=x) for x in user_term),
                    ~Q(pk__in=[]),
                ),
                reduce(
                    operator.and_,
                    (Q(author__contains=x) for x in author_term),
                    ~Q(pk__in=[]),
                ),
                reduce(
                    operator.and_,
                    (Q(publisher__contains=x) for x in publisher_term),
                    ~Q(pk__in=[]),
                ),
                reduce(
                    operator.and_,
                    (Q(total_time__gt=x) for x in time_gt_term),
                    ~Q(pk__in=[]),
                ),
                reduce(
                    operator.and_,
                    (Q(total_time__lt=x) for x in time_lt_term),
                    ~Q(pk__in=[]),
                ),
                reduce(
                    operator.and_,
                    (Q(total_time=x) for x in time_eq_term),
                    ~Q(pk__in=[]),
                ),
            )
        """| Q(keywords__contains=[x])"""
        return render(
            request,
            self.template_name,
            {"search_form": query, "search_results": search_results},
        )


def parse_iso8601_duration(iso_duration):
    if iso_duration is not None:
        maybe_timedelta = isodate.parse_duration(iso_duration)
        if isinstance(maybe_timedelta, timedelta):
            iso_duration = maybe_timedelta
    return iso_duration


class ParserInsertView(LoginRequiredMixin, View):
    template_name = "core/new.html"

    def get(self, request):
        parser_insert_form = ParserInsertForm()
        return render(request, self.template_name, {"form": parser_insert_form})

    def post(self, request):
        parser_insert_form = ParserInsertForm(request.POST)
        if not parser_insert_form.is_valid():
            return render(
                request, "core/new.html", {"form": parser_insert_form}
            )  # add form errors
        requested_url = parser_insert_form.cleaned_data["url"]
        request = requests.get(requested_url)
        parsed_html = BeautifulSoup(request.text, features="html.parser")
        ld_json = json.loads(
            parsed_html.find("script", attrs={"type": "application/ld+json"}).text
        )  # check if @type is Recipe
        recipe = Recipe(
            name=ld_json["name"],
            description=ld_json["description"],
            image=ld_json.get("image")
            if type(ld_json.get("image")) != list
            else ld_json["image"][-1],
            prep_time=parse_iso8601_duration(ld_json.get("prepTime")),
            cook_time=parse_iso8601_duration(ld_json.get("cookTime")),
            total_time=parse_iso8601_duration(ld_json.get("totalTime")),
            author=", ".join([author["name"] for author in ld_json["author"]])
            if type(ld_json["author"]) == list
            else ld_json["author"]["name"],
            keywords=ld_json["keywords"].split(", "),
            publisher=ld_json["publisher"]["name"],
            publisher_url=ld_json["publisher"].get("requested_url"),
            origin_url=requested_url,
            added_by=self.request.user,
        )
        recipe.save()

        try:
            ingredient_fill_in_obj = Ingredient.objects.get(name="(fill in)")
        except Ingredient.DoesNotExist:
            ingredient_fill_in_obj = Ingredient(name="(fill in)")
            ingredient_fill_in_obj.save()
        ingredients = [
            RecipeIngredient(
                recipe=recipe,
                ingredient=ingredient_fill_in_obj,
                quantity=None,
                description=raw_ingredient,
            )
            for raw_ingredient in ld_json["recipeIngredient"]
        ]
        RecipeIngredient.objects.bulk_create(ingredients)

        instructions = [
            RecipeInstruction(
                recipe=recipe, step_no=idx, text=ld_json_instruction["text"]
            )
            for idx, ld_json_instruction in enumerate(
                ld_json["recipeInstructions"], start=1
            )
        ]
        RecipeInstruction.objects.bulk_create(instructions)
        return redirect("core:edit", recipe_id=recipe.id)


class RecipeView(TemplateView):
    template_name = "core/recipe.html"

    def get_context_data(self, recipe_id, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context["recipe"] = Recipe.objects.get(pk=recipe_id)
        except Recipe.DoesNotExist:
            raise Http404
        return context


class EditView(View):
    def get(self, request, recipe_id):
        recipe = Recipe.objects.get(pk=recipe_id)
        recipe_form = RecipeForm(instance=recipe)

core/templates/core/about.html
{% extends "base_with_navbar.html" %}
{% load static %}

{% block body %}
	<div class="container">
		<div class="row">
			<div class="column">
				<h1 class="edit-title">about</h1>
				<p>nomsable is a sleek and smart recipe management software. Its main principles are to be not overwhelming and deliver smart recipe suggestions based on different circumstances and personal preferences. It brings a recipe parser for recipe websites and slim editor to archive a pleasant experience when adding recipes. Most websites provide plenty of overwhelming animations, windows and commercials, obfuscating their content. Nomsable tries to fix this issue. The multi user capability makes it perfect for small groups of people, e.g. shared apartments. The recipes themselves are presented on a single page with a readable, but thematically fitting font to eliminate the need for scrolling or touching your device while cooking. It also aims to be accessible and non confusing.</p>

				<p>You came here by clicking on <a class="navigation-title" href="{% url 'core:about' %}"> »about« </a>, click on <a class="navigation-title" href="{% url 'core:add' %}"> »add« </a> to add a new recipe by link, or on <a class="navigation-title" href="/preferences"> »preferences« </a> to change your preferences. Click on 
				<a class="navigation-title" href="{% url 'core:index' %}"> »nomsable« </a> to get back to the main page.</p>
			</div>
		</div>
	</div>
{% endblock %}

core/templates/core/detail.html
{% extends "base_with_navbar.html" %}

{% block body %}
<div class="container">
  {{ recipe.name }}
</div>
{% endblock body %}

core/templates/core/edit.html
{% extends "base_with_navbar.html" %}

{% block body %}
<div class="container">
  <form method="POST" class="post-form">
    {% csrf_token %}

    <div class="row recipe-title">
      <div class="column column-10"> <h1> edit </h1> </div>
      <div class="column">
        <span class="form-error">{{ recipe_form.name.errors.0 }}</span>
        {{ recipe_form.name }}
      </div>
    </div>

    <span class="form-error">{{ recipe_form.description.errors.0 }}</span>
    {{ recipe_form.description.label_tag }} {{ recipe_form.description }}
    <span class="form-error">{{ recipe_form.image.errors.0 }}</span>
    {{ recipe_form.image.label_tag }} {{ recipe_form.image }}

    <div class="row">
      <div class="column">
        <span class="form-error">{{ recipe_form.author.errors.0 }}</span>
        {{ recipe_form.author.label_tag }} {{ recipe_form.author }}
      </div>
      <div class="column">
        <span class="form-error">{{ recipe_form.origin_url.errors.0 }}</span>
        {{ recipe_form.origin_url.label_tag }} {{ recipe_form.origin_url }}
      </div>
    </div>

    <div class="row">
      <div class="column">
        <span class="form-error">{{ recipe_form.publisher.errors.0 }}</span>
        {{ recipe_form.publisher.label_tag }} {{ recipe_form.publisher }}
      </div>
      <div class="column">
        <span class="form-error">{{ recipe_form.publisher_url.errors.0 }}</span>
        {{ recipe_form.publisher_url.label_tag }} {{ recipe_form.publisher_url }}
      </div>
    </div>

    <div class="row">
      <div class="column">
        <span class="form-error">{{ recipe_form.prep_time.errors.0 }}</span>
        {{ recipe_form.prep_time.label_tag }} {{ recipe_form.prep_time }}
      </div>
      <div class="column">
        <span class="form-error">{{ recipe_form.cook_time.errors.0 }}</span>
        {{ recipe_form.cook_time.label_tag }} {{ recipe_form.cook_time }}
      </div>
      <div class="column">
        <span class="form-error">{{ recipe_form.total_time.errors.0 }}</span>
        {{ recipe_form.total_time.label_tag }} {{ recipe_form.total_time }}
      </div>
    </div>

    {{ recipe_tag_form.management_form }}
    {% for form in recipe_tag_form.forms %}
      {{ form.id }}
      {% if forloop.first %}
        <div class="row">
          <div class="column">
            {{ form.tag.label_tag }}
          </div>
          <div class="column column-10">
            {{ form.DELETE.label_tag }}
          </div>
        </div>
      {% endif %}
      <div class="row">
        <div class="column">
          <span class="form-error">{{ form.tag.errors.0 }}</span>
          {{ form.tag }}
        </div>
        <div class="column column-10">
          {{ form.DELETE }}
        </div>
      </div>
    {% endfor %}

    <h2 class="edit-title">ingredients:</h2>
    {{ ingredient_form.management_form }}
    {% for form in ingredient_form.forms %}
      {{ form.id }}
      {% if forloop.first %}
        <div class="row">
            <div class="column column-10"> {{ form.quantity.label_tag }} </div>
            <div class="column"> {{ form.ingredient.label_tag }} </div>
            <div class="column"> {{ form.description.label_tag }} </div>
            <div class="column column-10"> {{ form.DELETE.label_tag }} </div>
        </div>
      {% endif %}
      <div class="row">
        <div class="column column-10">
          <span class="form-error">{{ form.quantity.errors.0 }}</span>
          {{ form.quantity }}
        </div>
        <div class="column">
          <span class="form-error">{{ form.ingredient.errors.0 }}</span>
          {{ form.ingredient }}
        </div>
        <div class="column">
          <span class="form-error">{{ form.description.errors.0 }}</span>
          {{ form.description }}
        </div>
        <div class="column column-10">
          {{ form.DELETE }}
        </div>
      </div>
    {% endfor %}

    <h2 class="edit-title">steps:</h2>

    {{ instruction_form.management_form }}
    {% for form in instruction_form.forms %}
      {{ form.id }}
      {% if forloop.first %}
        <div class="row">
          <div class="column column-10"> {{ form.step_no.label_tag }} </div>
          <div class="column"> {{ form.text.label_tag }} </div>
          <div class="column column-10"> {{ form.DELETE.label_tag }} </div>
        </div>
      {% endif %}
      <div class="row">
        <div class="column column-10">
        <span class="form-error">{{ form.step_no.errors.0 }}</span>
        {{ form.step_no }}
      </div>
        <div class="column">
          <span class="form-error">{{ form.text.errors.0 }}</span>
          {{ form.text }}
        </div>
        <div class="column column-10">
          {{ form.DELETE }}
        </div>
      </div>
    {% endfor %}

    <button type="submit" class="save btn btn-default edit-title">Save</button>
  </form>
</div>
{% endblock body %}

core/templates/core/home.html
{% extends "base_with_navbar.html" %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="column frontpage-title">
      <h3>{{ greeting }} {{ user.name }}! {{ greeting_emoji }}</h3>
    </div>
  </div>
  <div class="row">
    <div class="column frontpage-search">
      <form method="POST" action="{% url 'core:search' %}" class="post-form">
        {% csrf_token %}
        <span class="form-error">{{ search_form.search.errors.0 }}</span>
        {{ search_form.search }}
      </form>
    </div>
  </div>
  <div class="row">
  	<div class="column"> <h4 class="">what to cook?</h4> </div>
  </div>
  {% for recipe in cook_next_recipes %}
    <div class="row">
      <div class="column column-3 frontpage-list"> {{ forloop.counter }}. </div>
      <div class="column column-5 frontpage-list">
        {% if recipe.image is not None %}
          <img src="{{ recipe.image }}" class="frontpage-image" alt="serving suggestion" title="serving suggestion">
        {% endif %}
      </div>
      <div class="column frontpage-list">
        <a href="{% url 'core:detail' recipe_id=recipe.pk %}">
          {{ recipe.name }}
          <small class="recipe-sub-title">
            {% if recipe.author != "" %} by {{ recipe.author }} {% endif %}
            {% if recipe.author != "" or recipe.publisher != "" %},&nbsp; {% endif %}
            {% if recipe.publisher != "" %} published by {{ recipe.publisher }} {% endif %}
          </small>
        </a>
      </div>
    </div>
  {% endfor %}
  <div class="row frontpage-title">
    <div class="column">
  <div class="row">
    <div class="column"> <h4 class="frontpage-title">latest recipes</h4> </div>
      </div>
      {% for recipe in latest_recipes %}
        <div class="row">
          <div class="column frontpage-list">
            <a href="{% url 'core:detail' recipe_id=recipe.pk %}">{{ recipe.name }}</a>
          </div>
        </div>
      {% endfor %}
    </div>
    <div class="column">
      <div class="row">
        <div class="column "> <h4 class="frontpage-title">most cooked</h4> </div>
      </div>
      {% for recipe in cook_next_recipes %}
        <div class="row">
          <div class="column frontpage-list">
            <a href="{% url 'core:detail' recipe_id=recipe.pk %}">{{ recipe.name }}</a>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock body %}

core/templates/core/new.html
{% extends "base_with_navbar.html" %}

{% block body %}
<div class="container">
    <h2>add recipe</h2>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button class="button">submit</button>
    </form>
</div>
{% endblock body %}

core/templates/core/recipe.html
{% extends "base_with_navbar.html" %}
{% load serve_duration %}

{% block body %}
<div class="container">
  <h2 class="recipe-title">{{ recipe.name }}</h2>
  {% if recipe.origin_url is not None %}<a href="{{ recipe.origin_url }}" target=_blank>{% endif %}
    <h5 class="recipe-sub-title">
      {% if recipe.author != "" %} by {{ recipe.author }} {% endif %}
      {% if recipe.author != "" or recipe.publisher != "" %},&nbsp; {% endif %}
      {% if recipe.publisher != "" %} published by {{ recipe.publisher }} {% endif %}
    </h5>
  {% if recipe.origin_url is not None %}</a>{% endif %}
  <div class="row">
    <div class="column column-33">
      <h4>ingredients</h4>
      <ul>
        {% for ingredient in recipe.ingredients.all %}
          {% if ingredient.ingredient.name != "" %}
            <li class="ingredient-list">
              {% if ingredient.quantity is not None %} {{ ingredient.quantity }} {% endif %}
              {{ ingredient.ingredient.name }}
              <small class="ingredient-description"> {% if ingredient.description is not None %} {{ ingredient.description }} {% endif %}</small>
            </li>
          {% endif %}
        {% endfor %}
      </ul>
      <div class="row">
        {% if recipe.prep_time is not None %} <div class="column"><small>Preperation time<br> {{ recipe.prep_time|serve_duration }}</small></div> {% endif %}
        {% if recipe.cook_time is not None %} <div class="column"><small>Cook time<br> {{ recipe.cook_time|serve_duration }}</small></div> {% endif %}
        {% if recipe.total_time is not None %} <div class="column"><small>Total time<br> {{ recipe.total_time|serve_duration }}</small></div> {% endif %}
      </div>
      <br>
      <a href="{% url 'core:edit' recipe_id=recipe.id %}"><small class="recipe-edit-link">edit this recipe</small></a>
      <br>
      <a href="{% url 'core:delete' recipe_id=recipe.id %}"><small class="recipe-delete-link">delete this recipe</small></a>
    </div>
    <div class="column">
      <h4>steps</h4>
      <div class="recipe-step-column">
        <ul>
          {% for step in recipe.instructions.all %}
          <li class="recipe-step">{{ step.text }}</li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
  <div class="row recipe-title">
    {% if recipe.description is not None %}
      <div class="column column-66">
        <h4>about the recipe</h4> {{ recipe.description }}
      </div>
    {% endif %}
    {% if recipe.description is not None %}
      <div class="column">
        <img src="{{ recipe.image }}" alt="serving suggestion" title="serving suggestion">
      </div>
    {% endif %}
  </div>
</div>
{% endblock body %}

core/templates/core/search.html
{% extends "base_with_navbar.html" %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="column frontpage-title">
            <h3>search</h3>
        </div>
    </div>
    <div class="row">
        <div class="column frontpage-search">
            <form method="POST" class="post-form">
                {% csrf_token %}
                <span class="form-error">{{ search_form.search.errors.0 }}</span>
                {{ search_form.search }}
            </form>
        </div>
    </div>
    {% for recipe in search_results %}
        <div class="row">
            <div class="column column-3 frontpage-list"> {{ forloop.counter }}. </div>
            <div class="column column-5 frontpage-list">
                {% if recipe.image is not None %}
                <img src="{{ recipe.image }}" class="frontpage-image" alt="serving suggestion" title="serving suggestion">
                {% endif %}
            </div>
            <div class="column frontpage-list">
                <a href="{% url 'core:detail' recipe_id=recipe.pk %}">
                    {{ recipe.name }}
                    <small class="recipe-sub-title">
                    {% if recipe.author != "" %} by {{ recipe.author }} {% endif %}
                    {% if recipe.author != "" or recipe.publisher != "" %},&nbsp; {% endif %}
                    {% if recipe.publisher != "" %} published by {{ recipe.publisher }} {% endif %}
                    </small>
                </a>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock body %}