accounts/urls.py
from django.urls import path

from accounts.views import auth, preferences

app_name = "accounts"
urlpatterns = [
    path("login/", auth.LoginView.as_view(), name="login"),
    path("signup/", auth.SignUpView.as_view(), name="signup"),
    path(
        "preferences/",
        preferences.PreferencesIndexView.as_view(),
        name="preferences_index",
    ),
    path(
        "preferences/create_invite_code",
        preferences.CreateInviteCodeView.as_view(),
        name="preferences_create_invite_code",
    ),
    path(
        "preferences/hide_recipes",
        preferences.PreferencesHideRecipesView.as_view(),
        name="preferences_hide_recipes",
    ),
]

core/urls.py
# core/urls.py

from django.urls import include, path

from . import views

app_name = "core"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("add", views.ParserInsertView.as_view(), name="add"),
    path("about", views.AboutView.as_view(), name="about"),
    path("search", views.SearchView.as_view(), name="search"),
    path("recipe/<int:recipe_id>", views.RecipeView.as_view(), name="detail"),
    path("recipe/<int:recipe_id>/edit", views.EditView.as_view(), name="edit"),
    path("recipe/<int:recipe_id>/delete", views.DeleteView.as_view(), name="delete"),
]

nomsable/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404

handler404 = 'core.views.error_404_view'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls', namespace='core')),
]

nomsable/templates/base.html
{% load compress %}
{% load static %}
<html lang="en">
    <head>
        <title>nomsable</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="author" content="Leona Maroni, Jana Marie Hemsing">
        <meta name="description" content="digital recipe management">
        <meta name="keywords" content="recipe, food, lunch, dinner, noms, ingredient">
        <link rel="icon" type="image/x-icon" href="{% static 'favicon.png' %}">
        <link rel="stylesheet" href="{% static 'base.css' %}">
        <link rel="stylesheet" href="{% static 'normalize.css' %}">
        {% compress css %}
            <link type="text/x-sass" href="{% static 'milligram/milligram.sass' %}" rel="stylesheet">
        {% endcompress %}
    </head>
    <body>
        <main class="wrapper">
            {% block main %}{% endblock %}
      </main>
    </body>
</html>

nomsable/templates/base_with_navbar.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <nav class="navigation">
        <section class="container">

            <a class="navigation-title" href="{% url 'core:index' %}">
                <img src="{% static 'logo.svg' %}" class="img">
                <h1 class="title">nomsable</h1>
            </a>

            <ul class="navigation-list float-right">
                <li class="navigation-item">
                    <a class="navigation-link" href="{% url 'core:about' %}" data-popover>about</a>
                </li>
                <li class="navigation-item">
                    <a class="navigation-link" href="{% url 'core:add' %}" data-popover>add</a>
                </li>
                <li class="navigation-item">
                    <a class="navigation-link" href="{% url 'accounts:preferences_index' %}" data-popover>preferences</a>
                </li>
            </ul>

        </section>
    </nav>

    {% block body %}{% endblock %}

    <footer class="footer">
    <section class="container">
        <p>
            Designed with ♥ by
            <a
                target="_blank"
                href="https://leona.is"
                title="Leona Maroni"
                >Leona Maroni</a
            > &
            <a
                target="_blank"
                href="https://janamarie.dev"
                title="Jana Marie Hemsing"
                >Jana Marie Hemsing</a
            >. Licensed under the
            <a
                target="_blank"
                href="https://github.com/leona-ya/nomsable#license"
                title="MIT License"
                >MIT License</a
            >.
        </p>
    </section>
  </footer>
{% endblock %}